package protocol.config.buffers;

import com.google.protobuf.UnknownFieldSet;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/config/protofiles/server_response.proto

public final class ServerResponse {
  private ServerResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    boolean hasResType();
    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    ServerResponse.Response.ResType getResType();

    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     *specify timestamp
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     *specify timestamp
     * </pre>
     */
    java.lang.String getTimestamp();
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     *specify timestamp
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    ServerResponse.Response.ReqResult getResult();
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    ServerResponse.Response.ReqResultOrBuilder getResultOrBuilder();

    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    boolean hasCallResponse();
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    ServerResponse.Response.CallResponse getCallResponse();
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    ServerResponse.Response.CallResponseOrBuilder getCallResponseOrBuilder();

    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    boolean hasEndCall();
    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    boolean getEndCall();
  }
  /**
   * Protobuf type {@code Response}
   *
   * <pre>
   *request structure
   * </pre>
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
    private static UnknownFieldSet unknownFields;

	// Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Response() {
      resType_ = 1;
      timestamp_ = "";
      endCall_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ServerResponse.Response.ResType value = ServerResponse.Response.ResType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              timestamp_ = bs;
              break;
            }
            case 26: {
              ServerResponse.Response.ReqResult.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(ServerResponse.Response.ReqResult.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              ServerResponse.Response.CallResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = callResponse_.toBuilder();
              }
              callResponse_ = input.readMessage(ServerResponse.Response.CallResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(callResponse_);
                callResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              endCall_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerResponse.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerResponse.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerResponse.Response.class, ServerResponse.Response.Builder.class);
    }

    public static final com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Response.ResType}
     *
     * <pre>
     *define the types of responses 
     * </pre>
     */
    public enum ResType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACT = 1;</code>
       */
      ACT(0, 1),
      /**
       * <code>CALL = 2;</code>
       */
      CALL(1, 2),
      /**
       * <code>ECALL = 3;</code>
       */
      ECALL(2, 3),
      ;

      /**
       * <code>ACT = 1;</code>
       */
      public static final int ACT_VALUE = 1;
      /**
       * <code>CALL = 2;</code>
       */
      public static final int CALL_VALUE = 2;
      /**
       * <code>ECALL = 3;</code>
       */
      public static final int ECALL_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      public static ResType valueOf(int value) {
        switch (value) {
          case 1: return ACT;
          case 2: return CALL;
          case 3: return ECALL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResType>() {
              public ResType findValueByNumber(int number) {
                return ResType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ServerResponse.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResType[] VALUES = values();

      public static ResType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Response.ResType)
    }

    public interface ReqResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Response.ReqResult)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required bool ok = 1;</code>
       */
      boolean hasOk();
      /**
       * <code>required bool ok = 1;</code>
       */
      boolean getOk();

      /**
       * <code>required string result = 2;</code>
       */
      boolean hasResult();
      /**
       * <code>required string result = 2;</code>
       */
      java.lang.String getResult();
      /**
       * <code>required string result = 2;</code>
       */
      com.google.protobuf.ByteString
          getResultBytes();
    }
    /**
     * Protobuf type {@code Response.ReqResult}
     *
     * <pre>
     *request result
     * </pre>
     */
    public  static final class ReqResult extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Response.ReqResult)
        ReqResultOrBuilder {
      private UnknownFieldSet unknownFields;

	// Use ReqResult.newBuilder() to construct.
      private ReqResult(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private ReqResult() {
        ok_ = false;
        result_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ReqResult(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                ok_ = input.readBool();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                result_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerResponse.internal_static_Response_ReqResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerResponse.internal_static_Response_ReqResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerResponse.Response.ReqResult.class, ServerResponse.Response.ReqResult.Builder.class);
      }

      public static final com.google.protobuf.Parser<ReqResult> PARSER =
          new com.google.protobuf.AbstractParser<ReqResult>() {
        public ReqResult parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqResult(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ReqResult> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int OK_FIELD_NUMBER = 1;
      private boolean ok_;
      /**
       * <code>required bool ok = 1;</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }

      public static final int RESULT_FIELD_NUMBER = 2;
      private java.lang.Object result_;
      /**
       * <code>required string result = 2;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string result = 2;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            result_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string result = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasOk()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasResult()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBool(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getResultBytes());
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getResultBytes());
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ServerResponse.Response.ReqResult parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ServerResponse.Response.ReqResult parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ServerResponse.Response.ReqResult parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ServerResponse.Response.ReqResult parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ServerResponse.Response.ReqResult parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ServerResponse.Response.ReqResult parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ServerResponse.Response.ReqResult prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Response.ReqResult}
       *
       * <pre>
       *request result
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Response.ReqResult)
          ServerResponse.Response.ReqResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ServerResponse.internal_static_Response_ReqResult_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ServerResponse.internal_static_Response_ReqResult_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ServerResponse.Response.ReqResult.class, ServerResponse.Response.ReqResult.Builder.class);
        }

        // Construct using ServerResponse.Response.ReqResult.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          ok_ = false;
          bitField0_ = (bitField0_ & ~0x00000001);
          result_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ServerResponse.internal_static_Response_ReqResult_descriptor;
        }

        public ServerResponse.Response.ReqResult getDefaultInstanceForType() {
          return ServerResponse.Response.ReqResult.getDefaultInstance();
        }

        public ServerResponse.Response.ReqResult build() {
          ServerResponse.Response.ReqResult result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ServerResponse.Response.ReqResult buildPartial() {
          ServerResponse.Response.ReqResult result = new ServerResponse.Response.ReqResult(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.ok_ = ok_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.result_ = result_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ServerResponse.Response.ReqResult) {
            return mergeFrom((ServerResponse.Response.ReqResult)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ServerResponse.Response.ReqResult other) {
          if (other == ServerResponse.Response.ReqResult.getDefaultInstance()) return this;
          if (other.hasOk()) {
            setOk(other.getOk());
          }
          if (other.hasResult()) {
            bitField0_ |= 0x00000002;
            result_ = other.result_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasOk()) {
            
            return false;
          }
          if (!hasResult()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ServerResponse.Response.ReqResult parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ServerResponse.Response.ReqResult) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private boolean ok_ ;
        /**
         * <code>required bool ok = 1;</code>
         */
        public boolean hasOk() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bool ok = 1;</code>
         */
        public boolean getOk() {
          return ok_;
        }
        /**
         * <code>required bool ok = 1;</code>
         */
        public Builder setOk(boolean value) {
          bitField0_ |= 0x00000001;
          ok_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool ok = 1;</code>
         */
        public Builder clearOk() {
          bitField0_ = (bitField0_ & ~0x00000001);
          ok_ = false;
          onChanged();
          return this;
        }

        private java.lang.Object result_ = "";
        /**
         * <code>required string result = 2;</code>
         */
        public boolean hasResult() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string result = 2;</code>
         */
        public java.lang.String getResult() {
          java.lang.Object ref = result_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              result_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string result = 2;</code>
         */
        public com.google.protobuf.ByteString
            getResultBytes() {
          java.lang.Object ref = result_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            result_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string result = 2;</code>
         */
        public Builder setResult(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          result_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string result = 2;</code>
         */
        public Builder clearResult() {
          bitField0_ = (bitField0_ & ~0x00000002);
          result_ = getDefaultInstance().getResult();
          onChanged();
          return this;
        }
        /**
         * <code>required string result = 2;</code>
         */
        public Builder setResultBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          result_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Response.ReqResult)
      }

      // @@protoc_insertion_point(class_scope:Response.ReqResult)
      private static final ServerResponse.Response.ReqResult defaultInstance;static {
        defaultInstance = new ServerResponse.Response.ReqResult();
      }

      public static ServerResponse.Response.ReqResult getDefaultInstance() {
        return defaultInstance;
      }

      public ServerResponse.Response.ReqResult getDefaultInstanceForType() {
        return defaultInstance;
      }

    }

    public interface CallResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Response.CallResponse)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required bool ok = 1;</code>
       */
      boolean hasOk();
      /**
       * <code>required bool ok = 1;</code>
       */
      boolean getOk();

      /**
       * <code>required string message = 2;</code>
       */
      boolean hasMessage();
      /**
       * <code>required string message = 2;</code>
       */
      java.lang.String getMessage();
      /**
       * <code>required string message = 2;</code>
       */
      com.google.protobuf.ByteString
          getMessageBytes();

      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      boolean hasIpAddress();
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      java.lang.String getIpAddress();
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      com.google.protobuf.ByteString
          getIpAddressBytes();
    }
    /**
     * Protobuf type {@code Response.CallResponse}
     *
     * <pre>
     *status response
     * </pre>
     */
    public  static final class CallResponse extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Response.CallResponse)
        CallResponseOrBuilder {
      private UnknownFieldSet unknownFields;

	// Use CallResponse.newBuilder() to construct.
      private CallResponse(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private CallResponse() {
        ok_ = false;
        message_ = "";
        ipAddress_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private CallResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                ok_ = input.readBool();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                message_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                ipAddress_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerResponse.internal_static_Response_CallResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerResponse.internal_static_Response_CallResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerResponse.Response.CallResponse.class, ServerResponse.Response.CallResponse.Builder.class);
      }

      public static final com.google.protobuf.Parser<CallResponse> PARSER =
          new com.google.protobuf.AbstractParser<CallResponse>() {
        public CallResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CallResponse(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CallResponse> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int OK_FIELD_NUMBER = 1;
      private boolean ok_;
      /**
       * <code>required bool ok = 1;</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }

      public static final int MESSAGE_FIELD_NUMBER = 2;
      private java.lang.Object message_;
      /**
       * <code>required string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IP_ADDRESS_FIELD_NUMBER = 3;
      private java.lang.Object ipAddress_;
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipAddress_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasOk()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMessage()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBool(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getMessageBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getIpAddressBytes());
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getMessageBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getIpAddressBytes());
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ServerResponse.Response.CallResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ServerResponse.Response.CallResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ServerResponse.Response.CallResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ServerResponse.Response.CallResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ServerResponse.Response.CallResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ServerResponse.Response.CallResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ServerResponse.Response.CallResponse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Response.CallResponse}
       *
       * <pre>
       *status response
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Response.CallResponse)
          ServerResponse.Response.CallResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ServerResponse.internal_static_Response_CallResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ServerResponse.internal_static_Response_CallResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ServerResponse.Response.CallResponse.class, ServerResponse.Response.CallResponse.Builder.class);
        }

        // Construct using ServerResponse.Response.CallResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          ok_ = false;
          bitField0_ = (bitField0_ & ~0x00000001);
          message_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          ipAddress_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ServerResponse.internal_static_Response_CallResponse_descriptor;
        }

        public ServerResponse.Response.CallResponse getDefaultInstanceForType() {
          return ServerResponse.Response.CallResponse.getDefaultInstance();
        }

        public ServerResponse.Response.CallResponse build() {
          ServerResponse.Response.CallResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ServerResponse.Response.CallResponse buildPartial() {
          ServerResponse.Response.CallResponse result = new ServerResponse.Response.CallResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.ok_ = ok_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.message_ = message_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.ipAddress_ = ipAddress_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ServerResponse.Response.CallResponse) {
            return mergeFrom((ServerResponse.Response.CallResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ServerResponse.Response.CallResponse other) {
          if (other == ServerResponse.Response.CallResponse.getDefaultInstance()) return this;
          if (other.hasOk()) {
            setOk(other.getOk());
          }
          if (other.hasMessage()) {
            bitField0_ |= 0x00000002;
            message_ = other.message_;
            onChanged();
          }
          if (other.hasIpAddress()) {
            bitField0_ |= 0x00000004;
            ipAddress_ = other.ipAddress_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasOk()) {
            
            return false;
          }
          if (!hasMessage()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ServerResponse.Response.CallResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ServerResponse.Response.CallResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private boolean ok_ ;
        /**
         * <code>required bool ok = 1;</code>
         */
        public boolean hasOk() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bool ok = 1;</code>
         */
        public boolean getOk() {
          return ok_;
        }
        /**
         * <code>required bool ok = 1;</code>
         */
        public Builder setOk(boolean value) {
          bitField0_ |= 0x00000001;
          ok_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool ok = 1;</code>
         */
        public Builder clearOk() {
          bitField0_ = (bitField0_ & ~0x00000001);
          ok_ = false;
          onChanged();
          return this;
        }

        private java.lang.Object message_ = "";
        /**
         * <code>required string message = 2;</code>
         */
        public boolean hasMessage() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string message = 2;</code>
         */
        public java.lang.String getMessage() {
          java.lang.Object ref = message_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              message_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string message = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMessageBytes() {
          java.lang.Object ref = message_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            message_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string message = 2;</code>
         */
        public Builder setMessage(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string message = 2;</code>
         */
        public Builder clearMessage() {
          bitField0_ = (bitField0_ & ~0x00000002);
          message_ = getDefaultInstance().getMessage();
          onChanged();
          return this;
        }
        /**
         * <code>required string message = 2;</code>
         */
        public Builder setMessageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object ipAddress_ = "";
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public boolean hasIpAddress() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public java.lang.String getIpAddress() {
          java.lang.Object ref = ipAddress_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              ipAddress_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public com.google.protobuf.ByteString
            getIpAddressBytes() {
          java.lang.Object ref = ipAddress_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ipAddress_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public Builder setIpAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          ipAddress_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public Builder clearIpAddress() {
          bitField0_ = (bitField0_ & ~0x00000004);
          ipAddress_ = getDefaultInstance().getIpAddress();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public Builder setIpAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          ipAddress_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Response.CallResponse)
      }

      // @@protoc_insertion_point(class_scope:Response.CallResponse)
      private static final ServerResponse.Response.CallResponse defaultInstance;static {
        defaultInstance = new ServerResponse.Response.CallResponse();
      }

      public static ServerResponse.Response.CallResponse getDefaultInstance() {
        return defaultInstance;
      }

      public ServerResponse.Response.CallResponse getDefaultInstanceForType() {
        return defaultInstance;
      }

    }

    private int bitField0_;
    public static final int RES_TYPE_FIELD_NUMBER = 1;
    private int resType_;
    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    public boolean hasResType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    public ServerResponse.Response.ResType getResType() {
      ServerResponse.Response.ResType result = ServerResponse.Response.ResType.valueOf(resType_);
      return result == null ? ServerResponse.Response.ResType.ACT : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private java.lang.Object timestamp_;
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     *specify timestamp
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     *specify timestamp
     * </pre>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     *specify timestamp
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private ServerResponse.Response.ReqResult result_;
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    public ServerResponse.Response.ReqResult getResult() {
      return result_ == null ? ServerResponse.Response.ReqResult.getDefaultInstance() : result_;
    }
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    public ServerResponse.Response.ReqResultOrBuilder getResultOrBuilder() {
      return result_ == null ? ServerResponse.Response.ReqResult.getDefaultInstance() : result_;
    }

    public static final int CALL_RESPONSE_FIELD_NUMBER = 4;
    private ServerResponse.Response.CallResponse callResponse_;
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    public boolean hasCallResponse() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    public ServerResponse.Response.CallResponse getCallResponse() {
      return callResponse_ == null ? ServerResponse.Response.CallResponse.getDefaultInstance() : callResponse_;
    }
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    public ServerResponse.Response.CallResponseOrBuilder getCallResponseOrBuilder() {
      return callResponse_ == null ? ServerResponse.Response.CallResponse.getDefaultInstance() : callResponse_;
    }

    public static final int ENDCALL_FIELD_NUMBER = 5;
    private boolean endCall_;
    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    public boolean hasEndCall() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    public boolean getEndCall() {
      return endCall_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasResult()) {
        if (!getResult().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCallResponse()) {
        if (!getCallResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getResult());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getCallResponse());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, endCall_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getResult());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCallResponse());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, endCall_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ServerResponse.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerResponse.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerResponse.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerResponse.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerResponse.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ServerResponse.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ServerResponse.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ServerResponse.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ServerResponse.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ServerResponse.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ServerResponse.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     *
     * <pre>
     *request structure
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        ServerResponse.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerResponse.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerResponse.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerResponse.Response.class, ServerResponse.Response.Builder.class);
      }

      // Construct using ServerResponse.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
          getCallResponseFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        resType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (resultBuilder_ == null) {
          result_ = null;
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (callResponseBuilder_ == null) {
          callResponse_ = null;
        } else {
          callResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        endCall_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerResponse.internal_static_Response_descriptor;
      }

      public ServerResponse.Response getDefaultInstanceForType() {
        return ServerResponse.Response.getDefaultInstance();
      }

      public ServerResponse.Response build() {
        ServerResponse.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServerResponse.Response buildPartial() {
        ServerResponse.Response result = new ServerResponse.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resType_ = resType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (callResponseBuilder_ == null) {
          result.callResponse_ = callResponse_;
        } else {
          result.callResponse_ = callResponseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.endCall_ = endCall_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServerResponse.Response) {
          return mergeFrom((ServerResponse.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServerResponse.Response other) {
        if (other == ServerResponse.Response.getDefaultInstance()) return this;
        if (other.hasResType()) {
          setResType(other.getResType());
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000002;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasCallResponse()) {
          mergeCallResponse(other.getCallResponse());
        }
        if (other.hasEndCall()) {
          setEndCall(other.getEndCall());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResType()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (hasResult()) {
          if (!getResult().isInitialized()) {
            
            return false;
          }
        }
        if (hasCallResponse()) {
          if (!getCallResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServerResponse.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServerResponse.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int resType_ = 1;
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public boolean hasResType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public ServerResponse.Response.ResType getResType() {
        ServerResponse.Response.ResType result = ServerResponse.Response.ResType.valueOf(resType_);
        return result == null ? ServerResponse.Response.ResType.ACT : result;
      }
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public Builder setResType(ServerResponse.Response.ResType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public Builder clearResType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       *specify timestamp
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       *specify timestamp
       * </pre>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       *specify timestamp
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       *specify timestamp
       * </pre>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       *specify timestamp
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       *specify timestamp
       * </pre>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }

      private ServerResponse.Response.ReqResult result_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          ServerResponse.Response.ReqResult, ServerResponse.Response.ReqResult.Builder, ServerResponse.Response.ReqResultOrBuilder> resultBuilder_;
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public ServerResponse.Response.ReqResult getResult() {
        if (resultBuilder_ == null) {
          return result_ == null ? ServerResponse.Response.ReqResult.getDefaultInstance() : result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder setResult(ServerResponse.Response.ReqResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder setResult(
          ServerResponse.Response.ReqResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder mergeResult(ServerResponse.Response.ReqResult value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              result_ != null &&
              result_ != ServerResponse.Response.ReqResult.getDefaultInstance()) {
            result_ =
              ServerResponse.Response.ReqResult.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = null;
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public ServerResponse.Response.ReqResult.Builder getResultBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public ServerResponse.Response.ReqResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_ == null ?
              ServerResponse.Response.ReqResult.getDefaultInstance() : result_;
        }
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ServerResponse.Response.ReqResult, ServerResponse.Response.ReqResult.Builder, ServerResponse.Response.ReqResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ServerResponse.Response.ReqResult, ServerResponse.Response.ReqResult.Builder, ServerResponse.Response.ReqResultOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      private ServerResponse.Response.CallResponse callResponse_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          ServerResponse.Response.CallResponse, ServerResponse.Response.CallResponse.Builder, ServerResponse.Response.CallResponseOrBuilder> callResponseBuilder_;
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public boolean hasCallResponse() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public ServerResponse.Response.CallResponse getCallResponse() {
        if (callResponseBuilder_ == null) {
          return callResponse_ == null ? ServerResponse.Response.CallResponse.getDefaultInstance() : callResponse_;
        } else {
          return callResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder setCallResponse(ServerResponse.Response.CallResponse value) {
        if (callResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callResponse_ = value;
          onChanged();
        } else {
          callResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder setCallResponse(
          ServerResponse.Response.CallResponse.Builder builderForValue) {
        if (callResponseBuilder_ == null) {
          callResponse_ = builderForValue.build();
          onChanged();
        } else {
          callResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder mergeCallResponse(ServerResponse.Response.CallResponse value) {
        if (callResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              callResponse_ != null &&
              callResponse_ != ServerResponse.Response.CallResponse.getDefaultInstance()) {
            callResponse_ =
              ServerResponse.Response.CallResponse.newBuilder(callResponse_).mergeFrom(value).buildPartial();
          } else {
            callResponse_ = value;
          }
          onChanged();
        } else {
          callResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder clearCallResponse() {
        if (callResponseBuilder_ == null) {
          callResponse_ = null;
          onChanged();
        } else {
          callResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public ServerResponse.Response.CallResponse.Builder getCallResponseBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getCallResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public ServerResponse.Response.CallResponseOrBuilder getCallResponseOrBuilder() {
        if (callResponseBuilder_ != null) {
          return callResponseBuilder_.getMessageOrBuilder();
        } else {
          return callResponse_ == null ?
              ServerResponse.Response.CallResponse.getDefaultInstance() : callResponse_;
        }
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ServerResponse.Response.CallResponse, ServerResponse.Response.CallResponse.Builder, ServerResponse.Response.CallResponseOrBuilder> 
          getCallResponseFieldBuilder() {
        if (callResponseBuilder_ == null) {
          callResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ServerResponse.Response.CallResponse, ServerResponse.Response.CallResponse.Builder, ServerResponse.Response.CallResponseOrBuilder>(
                  getCallResponse(),
                  getParentForChildren(),
                  isClean());
          callResponse_ = null;
        }
        return callResponseBuilder_;
      }

      private boolean endCall_ ;
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public boolean hasEndCall() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public boolean getEndCall() {
        return endCall_;
      }
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public Builder setEndCall(boolean value) {
        bitField0_ |= 0x00000010;
        endCall_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public Builder clearEndCall() {
        bitField0_ = (bitField0_ & ~0x00000010);
        endCall_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final ServerResponse.Response defaultInstance;static {
      defaultInstance = new ServerResponse.Response();
    }

    public static ServerResponse.Response getDefaultInstance() {
      return defaultInstance;
    }

    public ServerResponse.Response getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_ReqResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_ReqResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_CallResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_CallResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0protocol/config/protofiles/server_resp" +
      "onse.proto\"\272\002\n\010Response\022#\n\010res_type\030\001 \002(" +
      "\0162\021.Response.ResType\022\021\n\ttimestamp\030\002 \002(\t\022" +
      "#\n\006result\030\003 \001(\0132\023.Response.ReqResult\022-\n\r" +
      "call_response\030\004 \001(\0132\026.Response.CallRespo" +
      "nse\022\017\n\007endCall\030\005 \001(\010\032\'\n\tReqResult\022\n\n\002ok\030" +
      "\001 \002(\010\022\016\n\006result\030\002 \002(\t\032?\n\014CallResponse\022\n\n" +
      "\002ok\030\001 \002(\010\022\017\n\007message\030\002 \002(\t\022\022\n\nip_address" +
      "\030\003 \001(\t\"\'\n\007ResType\022\007\n\003ACT\020\001\022\010\n\004CALL\020\002\022\t\n\005" +
      "ECALL\020\003B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "ResType", "Timestamp", "Result", "CallResponse", "EndCall", });
    internal_static_Response_ReqResult_descriptor =
      internal_static_Response_descriptor.getNestedTypes().get(0);
    internal_static_Response_ReqResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_ReqResult_descriptor,
        new java.lang.String[] { "Ok", "Result", });
    internal_static_Response_CallResponse_descriptor =
      internal_static_Response_descriptor.getNestedTypes().get(1);
    internal_static_Response_CallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_CallResponse_descriptor,
        new java.lang.String[] { "Ok", "Message", "IpAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
