// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_response.proto

package protocol.config.buffers;

public final class ServerResponse {
  private ServerResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    boolean hasResType();
    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    protocol.config.buffers.ServerResponse.Response.ResType getResType();

    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    protocol.config.buffers.ServerResponse.Response.ReqResult getResult();
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    protocol.config.buffers.ServerResponse.Response.ReqResultOrBuilder getResultOrBuilder();

    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    boolean hasCallResponse();
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    protocol.config.buffers.ServerResponse.Response.CallResponse getCallResponse();
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    protocol.config.buffers.ServerResponse.Response.CallResponseOrBuilder getCallResponseOrBuilder();

    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    boolean hasEndCall();
    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    boolean getEndCall();
  }
  /**
   * Protobuf type {@code Response}
   *
   * <pre>
   *request structure
   * </pre>
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.config.buffers.ServerResponse.Response.ResType value = protocol.config.buffers.ServerResponse.Response.ResType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resType_ = value;
              }
              break;
            }
            case 26: {
              protocol.config.buffers.ServerResponse.Response.ReqResult.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(protocol.config.buffers.ServerResponse.Response.ReqResult.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              protocol.config.buffers.ServerResponse.Response.CallResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = callResponse_.toBuilder();
              }
              callResponse_ = input.readMessage(protocol.config.buffers.ServerResponse.Response.CallResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(callResponse_);
                callResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              endCall_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.config.buffers.ServerResponse.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.config.buffers.ServerResponse.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.config.buffers.ServerResponse.Response.class, protocol.config.buffers.ServerResponse.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Response.ResType}
     *
     * <pre>
     *define the types of responses 
     * </pre>
     */
    public enum ResType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACT = 1;</code>
       */
      ACT(0, 1),
      /**
       * <code>CALL = 2;</code>
       */
      CALL(1, 2),
      /**
       * <code>ECALL = 3;</code>
       */
      ECALL(2, 3),
      ;

      /**
       * <code>ACT = 1;</code>
       */
      public static final int ACT_VALUE = 1;
      /**
       * <code>CALL = 2;</code>
       */
      public static final int CALL_VALUE = 2;
      /**
       * <code>ECALL = 3;</code>
       */
      public static final int ECALL_VALUE = 3;


      public final int getNumber() { return value; }

      public static ResType valueOf(int value) {
        switch (value) {
          case 1: return ACT;
          case 2: return CALL;
          case 3: return ECALL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResType>() {
              public ResType findValueByNumber(int number) {
                return ResType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.config.buffers.ServerResponse.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResType[] VALUES = values();

      public static ResType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Response.ResType)
    }

    public interface ReqResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Response.ReqResult)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bool ok = 1;</code>
       */
      boolean hasOk();
      /**
       * <code>optional bool ok = 1;</code>
       */
      boolean getOk();

      /**
       * <code>optional string cause = 2;</code>
       */
      boolean hasCause();
      /**
       * <code>optional string cause = 2;</code>
       */
      java.lang.String getCause();
      /**
       * <code>optional string cause = 2;</code>
       */
      com.google.protobuf.ByteString
          getCauseBytes();
    }
    /**
     * Protobuf type {@code Response.ReqResult}
     *
     * <pre>
     *request result
     * </pre>
     */
    public static final class ReqResult extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Response.ReqResult)
        ReqResultOrBuilder {
      // Use ReqResult.newBuilder() to construct.
      private ReqResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ReqResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ReqResult defaultInstance;
      public static ReqResult getDefaultInstance() {
        return defaultInstance;
      }

      public ReqResult getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ReqResult(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                ok_ = input.readBool();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                cause_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.config.buffers.ServerResponse.internal_static_Response_ReqResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.config.buffers.ServerResponse.internal_static_Response_ReqResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.config.buffers.ServerResponse.Response.ReqResult.class, protocol.config.buffers.ServerResponse.Response.ReqResult.Builder.class);
      }

      public static com.google.protobuf.Parser<ReqResult> PARSER =
          new com.google.protobuf.AbstractParser<ReqResult>() {
        public ReqResult parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqResult(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ReqResult> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int OK_FIELD_NUMBER = 1;
      private boolean ok_;
      /**
       * <code>optional bool ok = 1;</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }

      public static final int CAUSE_FIELD_NUMBER = 2;
      private java.lang.Object cause_;
      /**
       * <code>optional string cause = 2;</code>
       */
      public boolean hasCause() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string cause = 2;</code>
       */
      public java.lang.String getCause() {
        java.lang.Object ref = cause_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cause_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string cause = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCauseBytes() {
        java.lang.Object ref = cause_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cause_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        ok_ = false;
        cause_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBool(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getCauseBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCauseBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protocol.config.buffers.ServerResponse.Response.ReqResult parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(protocol.config.buffers.ServerResponse.Response.ReqResult prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Response.ReqResult}
       *
       * <pre>
       *request result
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Response.ReqResult)
          protocol.config.buffers.ServerResponse.Response.ReqResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protocol.config.buffers.ServerResponse.internal_static_Response_ReqResult_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protocol.config.buffers.ServerResponse.internal_static_Response_ReqResult_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protocol.config.buffers.ServerResponse.Response.ReqResult.class, protocol.config.buffers.ServerResponse.Response.ReqResult.Builder.class);
        }

        // Construct using protocol.config.buffers.ServerResponse.Response.ReqResult.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          ok_ = false;
          bitField0_ = (bitField0_ & ~0x00000001);
          cause_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protocol.config.buffers.ServerResponse.internal_static_Response_ReqResult_descriptor;
        }

        public protocol.config.buffers.ServerResponse.Response.ReqResult getDefaultInstanceForType() {
          return protocol.config.buffers.ServerResponse.Response.ReqResult.getDefaultInstance();
        }

        public protocol.config.buffers.ServerResponse.Response.ReqResult build() {
          protocol.config.buffers.ServerResponse.Response.ReqResult result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protocol.config.buffers.ServerResponse.Response.ReqResult buildPartial() {
          protocol.config.buffers.ServerResponse.Response.ReqResult result = new protocol.config.buffers.ServerResponse.Response.ReqResult(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.ok_ = ok_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.cause_ = cause_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protocol.config.buffers.ServerResponse.Response.ReqResult) {
            return mergeFrom((protocol.config.buffers.ServerResponse.Response.ReqResult)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protocol.config.buffers.ServerResponse.Response.ReqResult other) {
          if (other == protocol.config.buffers.ServerResponse.Response.ReqResult.getDefaultInstance()) return this;
          if (other.hasOk()) {
            setOk(other.getOk());
          }
          if (other.hasCause()) {
            bitField0_ |= 0x00000002;
            cause_ = other.cause_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protocol.config.buffers.ServerResponse.Response.ReqResult parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protocol.config.buffers.ServerResponse.Response.ReqResult) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private boolean ok_ ;
        /**
         * <code>optional bool ok = 1;</code>
         */
        public boolean hasOk() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional bool ok = 1;</code>
         */
        public boolean getOk() {
          return ok_;
        }
        /**
         * <code>optional bool ok = 1;</code>
         */
        public Builder setOk(boolean value) {
          bitField0_ |= 0x00000001;
          ok_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool ok = 1;</code>
         */
        public Builder clearOk() {
          bitField0_ = (bitField0_ & ~0x00000001);
          ok_ = false;
          onChanged();
          return this;
        }

        private java.lang.Object cause_ = "";
        /**
         * <code>optional string cause = 2;</code>
         */
        public boolean hasCause() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public java.lang.String getCause() {
          java.lang.Object ref = cause_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              cause_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public com.google.protobuf.ByteString
            getCauseBytes() {
          java.lang.Object ref = cause_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            cause_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public Builder setCause(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          cause_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public Builder clearCause() {
          bitField0_ = (bitField0_ & ~0x00000002);
          cause_ = getDefaultInstance().getCause();
          onChanged();
          return this;
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public Builder setCauseBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          cause_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Response.ReqResult)
      }

      static {
        defaultInstance = new ReqResult(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Response.ReqResult)
    }

    public interface CallResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Response.CallResponse)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bool ok = 1;</code>
       */
      boolean hasOk();
      /**
       * <code>optional bool ok = 1;</code>
       */
      boolean getOk();

      /**
       * <code>optional string cause = 2;</code>
       */
      boolean hasCause();
      /**
       * <code>optional string cause = 2;</code>
       */
      java.lang.String getCause();
      /**
       * <code>optional string cause = 2;</code>
       */
      com.google.protobuf.ByteString
          getCauseBytes();

      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      boolean hasIpAddress();
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      java.lang.String getIpAddress();
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      com.google.protobuf.ByteString
          getIpAddressBytes();
    }
    /**
     * Protobuf type {@code Response.CallResponse}
     *
     * <pre>
     *status response
     * </pre>
     */
    public static final class CallResponse extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Response.CallResponse)
        CallResponseOrBuilder {
      // Use CallResponse.newBuilder() to construct.
      private CallResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private CallResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final CallResponse defaultInstance;
      public static CallResponse getDefaultInstance() {
        return defaultInstance;
      }

      public CallResponse getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private CallResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                ok_ = input.readBool();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                cause_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                ipAddress_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.config.buffers.ServerResponse.internal_static_Response_CallResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.config.buffers.ServerResponse.internal_static_Response_CallResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.config.buffers.ServerResponse.Response.CallResponse.class, protocol.config.buffers.ServerResponse.Response.CallResponse.Builder.class);
      }

      public static com.google.protobuf.Parser<CallResponse> PARSER =
          new com.google.protobuf.AbstractParser<CallResponse>() {
        public CallResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CallResponse(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CallResponse> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int OK_FIELD_NUMBER = 1;
      private boolean ok_;
      /**
       * <code>optional bool ok = 1;</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }

      public static final int CAUSE_FIELD_NUMBER = 2;
      private java.lang.Object cause_;
      /**
       * <code>optional string cause = 2;</code>
       */
      public boolean hasCause() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string cause = 2;</code>
       */
      public java.lang.String getCause() {
        java.lang.Object ref = cause_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cause_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string cause = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCauseBytes() {
        java.lang.Object ref = cause_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cause_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IP_ADDRESS_FIELD_NUMBER = 3;
      private java.lang.Object ipAddress_;
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipAddress_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ip_address = 3;</code>
       *
       * <pre>
       *if callee is online, we specify the ip address
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        ok_ = false;
        cause_ = "";
        ipAddress_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBool(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getCauseBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getIpAddressBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, ok_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCauseBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getIpAddressBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protocol.config.buffers.ServerResponse.Response.CallResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(protocol.config.buffers.ServerResponse.Response.CallResponse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Response.CallResponse}
       *
       * <pre>
       *status response
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Response.CallResponse)
          protocol.config.buffers.ServerResponse.Response.CallResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protocol.config.buffers.ServerResponse.internal_static_Response_CallResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protocol.config.buffers.ServerResponse.internal_static_Response_CallResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protocol.config.buffers.ServerResponse.Response.CallResponse.class, protocol.config.buffers.ServerResponse.Response.CallResponse.Builder.class);
        }

        // Construct using protocol.config.buffers.ServerResponse.Response.CallResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          ok_ = false;
          bitField0_ = (bitField0_ & ~0x00000001);
          cause_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          ipAddress_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protocol.config.buffers.ServerResponse.internal_static_Response_CallResponse_descriptor;
        }

        public protocol.config.buffers.ServerResponse.Response.CallResponse getDefaultInstanceForType() {
          return protocol.config.buffers.ServerResponse.Response.CallResponse.getDefaultInstance();
        }

        public protocol.config.buffers.ServerResponse.Response.CallResponse build() {
          protocol.config.buffers.ServerResponse.Response.CallResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protocol.config.buffers.ServerResponse.Response.CallResponse buildPartial() {
          protocol.config.buffers.ServerResponse.Response.CallResponse result = new protocol.config.buffers.ServerResponse.Response.CallResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.ok_ = ok_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.cause_ = cause_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.ipAddress_ = ipAddress_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protocol.config.buffers.ServerResponse.Response.CallResponse) {
            return mergeFrom((protocol.config.buffers.ServerResponse.Response.CallResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protocol.config.buffers.ServerResponse.Response.CallResponse other) {
          if (other == protocol.config.buffers.ServerResponse.Response.CallResponse.getDefaultInstance()) return this;
          if (other.hasOk()) {
            setOk(other.getOk());
          }
          if (other.hasCause()) {
            bitField0_ |= 0x00000002;
            cause_ = other.cause_;
            onChanged();
          }
          if (other.hasIpAddress()) {
            bitField0_ |= 0x00000004;
            ipAddress_ = other.ipAddress_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protocol.config.buffers.ServerResponse.Response.CallResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protocol.config.buffers.ServerResponse.Response.CallResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private boolean ok_ ;
        /**
         * <code>optional bool ok = 1;</code>
         */
        public boolean hasOk() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional bool ok = 1;</code>
         */
        public boolean getOk() {
          return ok_;
        }
        /**
         * <code>optional bool ok = 1;</code>
         */
        public Builder setOk(boolean value) {
          bitField0_ |= 0x00000001;
          ok_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool ok = 1;</code>
         */
        public Builder clearOk() {
          bitField0_ = (bitField0_ & ~0x00000001);
          ok_ = false;
          onChanged();
          return this;
        }

        private java.lang.Object cause_ = "";
        /**
         * <code>optional string cause = 2;</code>
         */
        public boolean hasCause() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public java.lang.String getCause() {
          java.lang.Object ref = cause_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              cause_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public com.google.protobuf.ByteString
            getCauseBytes() {
          java.lang.Object ref = cause_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            cause_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public Builder setCause(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          cause_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public Builder clearCause() {
          bitField0_ = (bitField0_ & ~0x00000002);
          cause_ = getDefaultInstance().getCause();
          onChanged();
          return this;
        }
        /**
         * <code>optional string cause = 2;</code>
         */
        public Builder setCauseBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          cause_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object ipAddress_ = "";
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public boolean hasIpAddress() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public java.lang.String getIpAddress() {
          java.lang.Object ref = ipAddress_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              ipAddress_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public com.google.protobuf.ByteString
            getIpAddressBytes() {
          java.lang.Object ref = ipAddress_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ipAddress_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public Builder setIpAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          ipAddress_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public Builder clearIpAddress() {
          bitField0_ = (bitField0_ & ~0x00000004);
          ipAddress_ = getDefaultInstance().getIpAddress();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ip_address = 3;</code>
         *
         * <pre>
         *if callee is online, we specify the ip address
         * </pre>
         */
        public Builder setIpAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          ipAddress_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Response.CallResponse)
      }

      static {
        defaultInstance = new CallResponse(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Response.CallResponse)
    }

    private int bitField0_;
    public static final int RES_TYPE_FIELD_NUMBER = 1;
    private protocol.config.buffers.ServerResponse.Response.ResType resType_;
    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    public boolean hasResType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Response.ResType res_type = 1;</code>
     *
     * <pre>
     *type of response
     * </pre>
     */
    public protocol.config.buffers.ServerResponse.Response.ResType getResType() {
      return resType_;
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private protocol.config.buffers.ServerResponse.Response.ReqResult result_;
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    public protocol.config.buffers.ServerResponse.Response.ReqResult getResult() {
      return result_;
    }
    /**
     * <code>optional .Response.ReqResult result = 3;</code>
     *
     * <pre>
     *responses for actions of REG, LIN, LOUT, ECALL
     * </pre>
     */
    public protocol.config.buffers.ServerResponse.Response.ReqResultOrBuilder getResultOrBuilder() {
      return result_;
    }

    public static final int CALL_RESPONSE_FIELD_NUMBER = 4;
    private protocol.config.buffers.ServerResponse.Response.CallResponse callResponse_;
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    public boolean hasCallResponse() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    public protocol.config.buffers.ServerResponse.Response.CallResponse getCallResponse() {
      return callResponse_;
    }
    /**
     * <code>optional .Response.CallResponse call_response = 4;</code>
     */
    public protocol.config.buffers.ServerResponse.Response.CallResponseOrBuilder getCallResponseOrBuilder() {
      return callResponse_;
    }

    public static final int ENDCALL_FIELD_NUMBER = 5;
    private boolean endCall_;
    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    public boolean hasEndCall() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool endCall = 5;</code>
     *
     * <pre>
     *this is used when two users are in a call and one of them wants to end the call
     *then a response will be sent to the other user saying that the call has ended
     *forcing him to close the UDP connection
     * </pre>
     */
    public boolean getEndCall() {
      return endCall_;
    }

    private void initFields() {
      resType_ = protocol.config.buffers.ServerResponse.Response.ResType.ACT;
      result_ = protocol.config.buffers.ServerResponse.Response.ReqResult.getDefaultInstance();
      callResponse_ = protocol.config.buffers.ServerResponse.Response.CallResponse.getDefaultInstance();
      endCall_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, callResponse_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(5, endCall_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, callResponse_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, endCall_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.config.buffers.ServerResponse.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.config.buffers.ServerResponse.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.config.buffers.ServerResponse.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.config.buffers.ServerResponse.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.config.buffers.ServerResponse.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.config.buffers.ServerResponse.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.config.buffers.ServerResponse.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.config.buffers.ServerResponse.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.config.buffers.ServerResponse.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.config.buffers.ServerResponse.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.config.buffers.ServerResponse.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     *
     * <pre>
     *request structure
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        protocol.config.buffers.ServerResponse.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.config.buffers.ServerResponse.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.config.buffers.ServerResponse.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.config.buffers.ServerResponse.Response.class, protocol.config.buffers.ServerResponse.Response.Builder.class);
      }

      // Construct using protocol.config.buffers.ServerResponse.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
          getCallResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resType_ = protocol.config.buffers.ServerResponse.Response.ResType.ACT;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (resultBuilder_ == null) {
          result_ = protocol.config.buffers.ServerResponse.Response.ReqResult.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (callResponseBuilder_ == null) {
          callResponse_ = protocol.config.buffers.ServerResponse.Response.CallResponse.getDefaultInstance();
        } else {
          callResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        endCall_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.config.buffers.ServerResponse.internal_static_Response_descriptor;
      }

      public protocol.config.buffers.ServerResponse.Response getDefaultInstanceForType() {
        return protocol.config.buffers.ServerResponse.Response.getDefaultInstance();
      }

      public protocol.config.buffers.ServerResponse.Response build() {
        protocol.config.buffers.ServerResponse.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.config.buffers.ServerResponse.Response buildPartial() {
        protocol.config.buffers.ServerResponse.Response result = new protocol.config.buffers.ServerResponse.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resType_ = resType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (callResponseBuilder_ == null) {
          result.callResponse_ = callResponse_;
        } else {
          result.callResponse_ = callResponseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endCall_ = endCall_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.config.buffers.ServerResponse.Response) {
          return mergeFrom((protocol.config.buffers.ServerResponse.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.config.buffers.ServerResponse.Response other) {
        if (other == protocol.config.buffers.ServerResponse.Response.getDefaultInstance()) return this;
        if (other.hasResType()) {
          setResType(other.getResType());
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasCallResponse()) {
          mergeCallResponse(other.getCallResponse());
        }
        if (other.hasEndCall()) {
          setEndCall(other.getEndCall());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.config.buffers.ServerResponse.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.config.buffers.ServerResponse.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol.config.buffers.ServerResponse.Response.ResType resType_ = protocol.config.buffers.ServerResponse.Response.ResType.ACT;
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public boolean hasResType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public protocol.config.buffers.ServerResponse.Response.ResType getResType() {
        return resType_;
      }
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public Builder setResType(protocol.config.buffers.ServerResponse.Response.ResType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Response.ResType res_type = 1;</code>
       *
       * <pre>
       *type of response
       * </pre>
       */
      public Builder clearResType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resType_ = protocol.config.buffers.ServerResponse.Response.ResType.ACT;
        onChanged();
        return this;
      }

      private protocol.config.buffers.ServerResponse.Response.ReqResult result_ = protocol.config.buffers.ServerResponse.Response.ReqResult.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.config.buffers.ServerResponse.Response.ReqResult, protocol.config.buffers.ServerResponse.Response.ReqResult.Builder, protocol.config.buffers.ServerResponse.Response.ReqResultOrBuilder> resultBuilder_;
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public protocol.config.buffers.ServerResponse.Response.ReqResult getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder setResult(protocol.config.buffers.ServerResponse.Response.ReqResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder setResult(
          protocol.config.buffers.ServerResponse.Response.ReqResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder mergeResult(protocol.config.buffers.ServerResponse.Response.ReqResult value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              result_ != protocol.config.buffers.ServerResponse.Response.ReqResult.getDefaultInstance()) {
            result_ =
              protocol.config.buffers.ServerResponse.Response.ReqResult.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = protocol.config.buffers.ServerResponse.Response.ReqResult.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public protocol.config.buffers.ServerResponse.Response.ReqResult.Builder getResultBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      public protocol.config.buffers.ServerResponse.Response.ReqResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>optional .Response.ReqResult result = 3;</code>
       *
       * <pre>
       *responses for actions of REG, LIN, LOUT, ECALL
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.config.buffers.ServerResponse.Response.ReqResult, protocol.config.buffers.ServerResponse.Response.ReqResult.Builder, protocol.config.buffers.ServerResponse.Response.ReqResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.config.buffers.ServerResponse.Response.ReqResult, protocol.config.buffers.ServerResponse.Response.ReqResult.Builder, protocol.config.buffers.ServerResponse.Response.ReqResultOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      private protocol.config.buffers.ServerResponse.Response.CallResponse callResponse_ = protocol.config.buffers.ServerResponse.Response.CallResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.config.buffers.ServerResponse.Response.CallResponse, protocol.config.buffers.ServerResponse.Response.CallResponse.Builder, protocol.config.buffers.ServerResponse.Response.CallResponseOrBuilder> callResponseBuilder_;
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public boolean hasCallResponse() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public protocol.config.buffers.ServerResponse.Response.CallResponse getCallResponse() {
        if (callResponseBuilder_ == null) {
          return callResponse_;
        } else {
          return callResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder setCallResponse(protocol.config.buffers.ServerResponse.Response.CallResponse value) {
        if (callResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callResponse_ = value;
          onChanged();
        } else {
          callResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder setCallResponse(
          protocol.config.buffers.ServerResponse.Response.CallResponse.Builder builderForValue) {
        if (callResponseBuilder_ == null) {
          callResponse_ = builderForValue.build();
          onChanged();
        } else {
          callResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder mergeCallResponse(protocol.config.buffers.ServerResponse.Response.CallResponse value) {
        if (callResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              callResponse_ != protocol.config.buffers.ServerResponse.Response.CallResponse.getDefaultInstance()) {
            callResponse_ =
              protocol.config.buffers.ServerResponse.Response.CallResponse.newBuilder(callResponse_).mergeFrom(value).buildPartial();
          } else {
            callResponse_ = value;
          }
          onChanged();
        } else {
          callResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public Builder clearCallResponse() {
        if (callResponseBuilder_ == null) {
          callResponse_ = protocol.config.buffers.ServerResponse.Response.CallResponse.getDefaultInstance();
          onChanged();
        } else {
          callResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public protocol.config.buffers.ServerResponse.Response.CallResponse.Builder getCallResponseBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCallResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      public protocol.config.buffers.ServerResponse.Response.CallResponseOrBuilder getCallResponseOrBuilder() {
        if (callResponseBuilder_ != null) {
          return callResponseBuilder_.getMessageOrBuilder();
        } else {
          return callResponse_;
        }
      }
      /**
       * <code>optional .Response.CallResponse call_response = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.config.buffers.ServerResponse.Response.CallResponse, protocol.config.buffers.ServerResponse.Response.CallResponse.Builder, protocol.config.buffers.ServerResponse.Response.CallResponseOrBuilder> 
          getCallResponseFieldBuilder() {
        if (callResponseBuilder_ == null) {
          callResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.config.buffers.ServerResponse.Response.CallResponse, protocol.config.buffers.ServerResponse.Response.CallResponse.Builder, protocol.config.buffers.ServerResponse.Response.CallResponseOrBuilder>(
                  getCallResponse(),
                  getParentForChildren(),
                  isClean());
          callResponse_ = null;
        }
        return callResponseBuilder_;
      }

      private boolean endCall_ ;
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public boolean hasEndCall() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public boolean getEndCall() {
        return endCall_;
      }
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public Builder setEndCall(boolean value) {
        bitField0_ |= 0x00000008;
        endCall_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool endCall = 5;</code>
       *
       * <pre>
       *this is used when two users are in a call and one of them wants to end the call
       *then a response will be sent to the other user saying that the call has ended
       *forcing him to close the UDP connection
       * </pre>
       */
      public Builder clearEndCall() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endCall_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_ReqResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_ReqResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_CallResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_CallResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025server_response.proto\"\244\002\n\010Response\022#\n\010" +
      "res_type\030\001 \002(\0162\021.Response.ResType\022#\n\006res" +
      "ult\030\003 \001(\0132\023.Response.ReqResult\022-\n\rcall_r" +
      "esponse\030\004 \001(\0132\026.Response.CallResponse\022\017\n" +
      "\007endCall\030\005 \001(\010\032&\n\tReqResult\022\n\n\002ok\030\001 \001(\010\022" +
      "\r\n\005cause\030\002 \001(\t\032=\n\014CallResponse\022\n\n\002ok\030\001 \001" +
      "(\010\022\r\n\005cause\030\002 \001(\t\022\022\n\nip_address\030\003 \001(\t\"\'\n" +
      "\007ResType\022\007\n\003ACT\020\001\022\010\n\004CALL\020\002\022\t\n\005ECALL\020\003B\033" +
      "\n\027protocol.config.buffersH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "ResType", "Result", "CallResponse", "EndCall", });
    internal_static_Response_ReqResult_descriptor =
      internal_static_Response_descriptor.getNestedTypes().get(0);
    internal_static_Response_ReqResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_ReqResult_descriptor,
        new java.lang.String[] { "Ok", "Cause", });
    internal_static_Response_CallResponse_descriptor =
      internal_static_Response_descriptor.getNestedTypes().get(1);
    internal_static_Response_CallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_CallResponse_descriptor,
        new java.lang.String[] { "Ok", "Cause", "IpAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
