// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_request.proto

package buffers;

public final class ClientRequest {
  private ClientRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Request.ReqType rq_type = 1;</code>
     *
     * <pre>
     *request type is required
     * </pre>
     */
    boolean hasRqType();
    /**
     * <code>required .Request.ReqType rq_type = 1;</code>
     *
     * <pre>
     *request type is required
     * </pre>
     */
    buffers.ClientRequest.Request.ReqType getRqType();

    /**
     * <code>optional .Request.Registration reg = 3;</code>
     *
     * <pre>
     *registration message will be filled in for type REG
     * </pre>
     */
    boolean hasReg();
    /**
     * <code>optional .Request.Registration reg = 3;</code>
     *
     * <pre>
     *registration message will be filled in for type REG
     * </pre>
     */
    buffers.ClientRequest.Request.Registration getReg();
    /**
     * <code>optional .Request.Registration reg = 3;</code>
     *
     * <pre>
     *registration message will be filled in for type REG
     * </pre>
     */
    buffers.ClientRequest.Request.RegistrationOrBuilder getRegOrBuilder();

    /**
     * <code>optional .Request.LogIn lin = 4;</code>
     *
     * <pre>
     *login message will be filled in for type LIN
     * </pre>
     */
    boolean hasLin();
    /**
     * <code>optional .Request.LogIn lin = 4;</code>
     *
     * <pre>
     *login message will be filled in for type LIN
     * </pre>
     */
    buffers.ClientRequest.Request.LogIn getLin();
    /**
     * <code>optional .Request.LogIn lin = 4;</code>
     *
     * <pre>
     *login message will be filled in for type LIN
     * </pre>
     */
    buffers.ClientRequest.Request.LogInOrBuilder getLinOrBuilder();

    /**
     * <code>optional string username = 5;</code>
     *
     * <pre>
     *username field will be filled in for types CALL, ADDF, DELF
     * </pre>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 5;</code>
     *
     * <pre>
     *username field will be filled in for types CALL, ADDF, DELF
     * </pre>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 5;</code>
     *
     * <pre>
     *username field will be filled in for types CALL, ADDF, DELF
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional bool confirmation = 6;</code>
     *
     * <pre>
     *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
     * </pre>
     */
    boolean hasConfirmation();
    /**
     * <code>optional bool confirmation = 6;</code>
     *
     * <pre>
     *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
     * </pre>
     */
    boolean getConfirmation();
  }
  /**
   * Protobuf type {@code Request}
   *
   * <pre>
   *request structure
   * </pre>
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              buffers.ClientRequest.Request.ReqType value = buffers.ClientRequest.Request.ReqType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                rqType_ = value;
              }
              break;
            }
            case 26: {
              buffers.ClientRequest.Request.Registration.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = reg_.toBuilder();
              }
              reg_ = input.readMessage(buffers.ClientRequest.Request.Registration.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reg_);
                reg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              buffers.ClientRequest.Request.LogIn.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = lin_.toBuilder();
              }
              lin_ = input.readMessage(buffers.ClientRequest.Request.LogIn.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lin_);
                lin_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              username_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              confirmation_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffers.ClientRequest.internal_static_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffers.ClientRequest.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buffers.ClientRequest.Request.class, buffers.ClientRequest.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Request.ReqType}
     *
     * <pre>
     *specify the type of request
     * </pre>
     */
    public enum ReqType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REG = 1;</code>
       */
      REG(0, 1),
      /**
       * <code>LIN = 2;</code>
       */
      LIN(1, 2),
      /**
       * <code>LOUT = 3;</code>
       */
      LOUT(2, 3),
      /**
       * <code>CALL = 4;</code>
       */
      CALL(3, 4),
      /**
       * <code>CALLRES = 5;</code>
       */
      CALLRES(4, 5),
      /**
       * <code>ECALL = 6;</code>
       */
      ECALL(5, 6),
      /**
       * <code>FLIST = 7;</code>
       */
      FLIST(6, 7),
      /**
       * <code>ADDF = 8;</code>
       */
      ADDF(7, 8),
      /**
       * <code>DELF = 9;</code>
       */
      DELF(8, 9),
      ;

      /**
       * <code>REG = 1;</code>
       */
      public static final int REG_VALUE = 1;
      /**
       * <code>LIN = 2;</code>
       */
      public static final int LIN_VALUE = 2;
      /**
       * <code>LOUT = 3;</code>
       */
      public static final int LOUT_VALUE = 3;
      /**
       * <code>CALL = 4;</code>
       */
      public static final int CALL_VALUE = 4;
      /**
       * <code>CALLRES = 5;</code>
       */
      public static final int CALLRES_VALUE = 5;
      /**
       * <code>ECALL = 6;</code>
       */
      public static final int ECALL_VALUE = 6;
      /**
       * <code>FLIST = 7;</code>
       */
      public static final int FLIST_VALUE = 7;
      /**
       * <code>ADDF = 8;</code>
       */
      public static final int ADDF_VALUE = 8;
      /**
       * <code>DELF = 9;</code>
       */
      public static final int DELF_VALUE = 9;


      public final int getNumber() { return value; }

      public static ReqType valueOf(int value) {
        switch (value) {
          case 1: return REG;
          case 2: return LIN;
          case 3: return LOUT;
          case 4: return CALL;
          case 5: return CALLRES;
          case 6: return ECALL;
          case 7: return FLIST;
          case 8: return ADDF;
          case 9: return DELF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ReqType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ReqType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ReqType>() {
              public ReqType findValueByNumber(int number) {
                return ReqType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return buffers.ClientRequest.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final ReqType[] VALUES = values();

      public static ReqType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ReqType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Request.ReqType)
    }

    public interface RegistrationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Request.Registration)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for registration
       * </pre>
       */
      boolean hasUsername();
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for registration
       * </pre>
       */
      java.lang.String getUsername();
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for registration
       * </pre>
       */
      com.google.protobuf.ByteString
          getUsernameBytes();

      /**
       * <code>required string password = 2;</code>
       */
      boolean hasPassword();
      /**
       * <code>required string password = 2;</code>
       */
      java.lang.String getPassword();
      /**
       * <code>required string password = 2;</code>
       */
      com.google.protobuf.ByteString
          getPasswordBytes();

      /**
       * <code>optional string hint = 3;</code>
       */
      boolean hasHint();
      /**
       * <code>optional string hint = 3;</code>
       */
      java.lang.String getHint();
      /**
       * <code>optional string hint = 3;</code>
       */
      com.google.protobuf.ByteString
          getHintBytes();
    }
    /**
     * Protobuf type {@code Request.Registration}
     *
     * <pre>
     *registration request structure
     * </pre>
     */
    public static final class Registration extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Request.Registration)
        RegistrationOrBuilder {
      // Use Registration.newBuilder() to construct.
      private Registration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Registration(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Registration defaultInstance;
      public static Registration getDefaultInstance() {
        return defaultInstance;
      }

      public Registration getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Registration(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                username_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                password_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                hint_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffers.ClientRequest.internal_static_Request_Registration_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffers.ClientRequest.internal_static_Request_Registration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buffers.ClientRequest.Request.Registration.class, buffers.ClientRequest.Request.Registration.Builder.class);
      }

      public static com.google.protobuf.Parser<Registration> PARSER =
          new com.google.protobuf.AbstractParser<Registration>() {
        public Registration parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Registration(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Registration> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int USERNAME_FIELD_NUMBER = 1;
      private java.lang.Object username_;
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for registration
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for registration
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for registration
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PASSWORD_FIELD_NUMBER = 2;
      private java.lang.Object password_;
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int HINT_FIELD_NUMBER = 3;
      private java.lang.Object hint_;
      /**
       * <code>optional string hint = 3;</code>
       */
      public boolean hasHint() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string hint = 3;</code>
       */
      public java.lang.String getHint() {
        java.lang.Object ref = hint_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hint_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string hint = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHintBytes() {
        java.lang.Object ref = hint_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        username_ = "";
        password_ = "";
        hint_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasUsername()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPassword()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getUsernameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPasswordBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getHintBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUsernameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPasswordBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getHintBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static buffers.ClientRequest.Request.Registration parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.ClientRequest.Request.Registration parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.Registration parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.ClientRequest.Request.Registration parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.Registration parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static buffers.ClientRequest.Request.Registration parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.Registration parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static buffers.ClientRequest.Request.Registration parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.Registration parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static buffers.ClientRequest.Request.Registration parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(buffers.ClientRequest.Request.Registration prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Request.Registration}
       *
       * <pre>
       *registration request structure
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Request.Registration)
          buffers.ClientRequest.Request.RegistrationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return buffers.ClientRequest.internal_static_Request_Registration_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return buffers.ClientRequest.internal_static_Request_Registration_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  buffers.ClientRequest.Request.Registration.class, buffers.ClientRequest.Request.Registration.Builder.class);
        }

        // Construct using buffers.ClientRequest.Request.Registration.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          username_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          password_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          hint_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return buffers.ClientRequest.internal_static_Request_Registration_descriptor;
        }

        public buffers.ClientRequest.Request.Registration getDefaultInstanceForType() {
          return buffers.ClientRequest.Request.Registration.getDefaultInstance();
        }

        public buffers.ClientRequest.Request.Registration build() {
          buffers.ClientRequest.Request.Registration result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public buffers.ClientRequest.Request.Registration buildPartial() {
          buffers.ClientRequest.Request.Registration result = new buffers.ClientRequest.Request.Registration(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.username_ = username_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.password_ = password_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.hint_ = hint_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof buffers.ClientRequest.Request.Registration) {
            return mergeFrom((buffers.ClientRequest.Request.Registration)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(buffers.ClientRequest.Request.Registration other) {
          if (other == buffers.ClientRequest.Request.Registration.getDefaultInstance()) return this;
          if (other.hasUsername()) {
            bitField0_ |= 0x00000001;
            username_ = other.username_;
            onChanged();
          }
          if (other.hasPassword()) {
            bitField0_ |= 0x00000002;
            password_ = other.password_;
            onChanged();
          }
          if (other.hasHint()) {
            bitField0_ |= 0x00000004;
            hint_ = other.hint_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasUsername()) {
            
            return false;
          }
          if (!hasPassword()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          buffers.ClientRequest.Request.Registration parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (buffers.ClientRequest.Request.Registration) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object username_ = "";
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for registration
         * </pre>
         */
        public boolean hasUsername() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for registration
         * </pre>
         */
        public java.lang.String getUsername() {
          java.lang.Object ref = username_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              username_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for registration
         * </pre>
         */
        public com.google.protobuf.ByteString
            getUsernameBytes() {
          java.lang.Object ref = username_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            username_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for registration
         * </pre>
         */
        public Builder setUsername(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          username_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for registration
         * </pre>
         */
        public Builder clearUsername() {
          bitField0_ = (bitField0_ & ~0x00000001);
          username_ = getDefaultInstance().getUsername();
          onChanged();
          return this;
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for registration
         * </pre>
         */
        public Builder setUsernameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          username_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object password_ = "";
        /**
         * <code>required string password = 2;</code>
         */
        public boolean hasPassword() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string password = 2;</code>
         */
        public java.lang.String getPassword() {
          java.lang.Object ref = password_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              password_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string password = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPasswordBytes() {
          java.lang.Object ref = password_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            password_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string password = 2;</code>
         */
        public Builder setPassword(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          password_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string password = 2;</code>
         */
        public Builder clearPassword() {
          bitField0_ = (bitField0_ & ~0x00000002);
          password_ = getDefaultInstance().getPassword();
          onChanged();
          return this;
        }
        /**
         * <code>required string password = 2;</code>
         */
        public Builder setPasswordBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          password_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object hint_ = "";
        /**
         * <code>optional string hint = 3;</code>
         */
        public boolean hasHint() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string hint = 3;</code>
         */
        public java.lang.String getHint() {
          java.lang.Object ref = hint_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              hint_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string hint = 3;</code>
         */
        public com.google.protobuf.ByteString
            getHintBytes() {
          java.lang.Object ref = hint_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            hint_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string hint = 3;</code>
         */
        public Builder setHint(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          hint_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string hint = 3;</code>
         */
        public Builder clearHint() {
          bitField0_ = (bitField0_ & ~0x00000004);
          hint_ = getDefaultInstance().getHint();
          onChanged();
          return this;
        }
        /**
         * <code>optional string hint = 3;</code>
         */
        public Builder setHintBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          hint_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Request.Registration)
      }

      static {
        defaultInstance = new Registration(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Request.Registration)
    }

    public interface LogInOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Request.LogIn)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for log in
       * </pre>
       */
      boolean hasUsername();
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for log in
       * </pre>
       */
      java.lang.String getUsername();
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for log in
       * </pre>
       */
      com.google.protobuf.ByteString
          getUsernameBytes();

      /**
       * <code>required string password = 2;</code>
       */
      boolean hasPassword();
      /**
       * <code>required string password = 2;</code>
       */
      java.lang.String getPassword();
      /**
       * <code>required string password = 2;</code>
       */
      com.google.protobuf.ByteString
          getPasswordBytes();
    }
    /**
     * Protobuf type {@code Request.LogIn}
     *
     * <pre>
     *log in request structure
     * </pre>
     */
    public static final class LogIn extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Request.LogIn)
        LogInOrBuilder {
      // Use LogIn.newBuilder() to construct.
      private LogIn(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private LogIn(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final LogIn defaultInstance;
      public static LogIn getDefaultInstance() {
        return defaultInstance;
      }

      public LogIn getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private LogIn(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                username_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                password_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffers.ClientRequest.internal_static_Request_LogIn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffers.ClientRequest.internal_static_Request_LogIn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buffers.ClientRequest.Request.LogIn.class, buffers.ClientRequest.Request.LogIn.Builder.class);
      }

      public static com.google.protobuf.Parser<LogIn> PARSER =
          new com.google.protobuf.AbstractParser<LogIn>() {
        public LogIn parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogIn(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LogIn> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int USERNAME_FIELD_NUMBER = 1;
      private java.lang.Object username_;
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for log in
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for log in
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       *fields for log in
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PASSWORD_FIELD_NUMBER = 2;
      private java.lang.Object password_;
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        username_ = "";
        password_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasUsername()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPassword()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getUsernameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPasswordBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUsernameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPasswordBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static buffers.ClientRequest.Request.LogIn parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.ClientRequest.Request.LogIn parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.LogIn parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.ClientRequest.Request.LogIn parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.LogIn parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static buffers.ClientRequest.Request.LogIn parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.LogIn parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static buffers.ClientRequest.Request.LogIn parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static buffers.ClientRequest.Request.LogIn parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static buffers.ClientRequest.Request.LogIn parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(buffers.ClientRequest.Request.LogIn prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Request.LogIn}
       *
       * <pre>
       *log in request structure
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Request.LogIn)
          buffers.ClientRequest.Request.LogInOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return buffers.ClientRequest.internal_static_Request_LogIn_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return buffers.ClientRequest.internal_static_Request_LogIn_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  buffers.ClientRequest.Request.LogIn.class, buffers.ClientRequest.Request.LogIn.Builder.class);
        }

        // Construct using buffers.ClientRequest.Request.LogIn.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          username_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          password_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return buffers.ClientRequest.internal_static_Request_LogIn_descriptor;
        }

        public buffers.ClientRequest.Request.LogIn getDefaultInstanceForType() {
          return buffers.ClientRequest.Request.LogIn.getDefaultInstance();
        }

        public buffers.ClientRequest.Request.LogIn build() {
          buffers.ClientRequest.Request.LogIn result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public buffers.ClientRequest.Request.LogIn buildPartial() {
          buffers.ClientRequest.Request.LogIn result = new buffers.ClientRequest.Request.LogIn(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.username_ = username_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.password_ = password_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof buffers.ClientRequest.Request.LogIn) {
            return mergeFrom((buffers.ClientRequest.Request.LogIn)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(buffers.ClientRequest.Request.LogIn other) {
          if (other == buffers.ClientRequest.Request.LogIn.getDefaultInstance()) return this;
          if (other.hasUsername()) {
            bitField0_ |= 0x00000001;
            username_ = other.username_;
            onChanged();
          }
          if (other.hasPassword()) {
            bitField0_ |= 0x00000002;
            password_ = other.password_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasUsername()) {
            
            return false;
          }
          if (!hasPassword()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          buffers.ClientRequest.Request.LogIn parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (buffers.ClientRequest.Request.LogIn) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object username_ = "";
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for log in
         * </pre>
         */
        public boolean hasUsername() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for log in
         * </pre>
         */
        public java.lang.String getUsername() {
          java.lang.Object ref = username_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              username_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for log in
         * </pre>
         */
        public com.google.protobuf.ByteString
            getUsernameBytes() {
          java.lang.Object ref = username_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            username_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for log in
         * </pre>
         */
        public Builder setUsername(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          username_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for log in
         * </pre>
         */
        public Builder clearUsername() {
          bitField0_ = (bitField0_ & ~0x00000001);
          username_ = getDefaultInstance().getUsername();
          onChanged();
          return this;
        }
        /**
         * <code>required string username = 1;</code>
         *
         * <pre>
         *fields for log in
         * </pre>
         */
        public Builder setUsernameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          username_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object password_ = "";
        /**
         * <code>required string password = 2;</code>
         */
        public boolean hasPassword() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string password = 2;</code>
         */
        public java.lang.String getPassword() {
          java.lang.Object ref = password_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              password_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string password = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPasswordBytes() {
          java.lang.Object ref = password_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            password_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string password = 2;</code>
         */
        public Builder setPassword(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          password_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string password = 2;</code>
         */
        public Builder clearPassword() {
          bitField0_ = (bitField0_ & ~0x00000002);
          password_ = getDefaultInstance().getPassword();
          onChanged();
          return this;
        }
        /**
         * <code>required string password = 2;</code>
         */
        public Builder setPasswordBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          password_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Request.LogIn)
      }

      static {
        defaultInstance = new LogIn(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Request.LogIn)
    }

    private int bitField0_;
    public static final int RQ_TYPE_FIELD_NUMBER = 1;
    private buffers.ClientRequest.Request.ReqType rqType_;
    /**
     * <code>required .Request.ReqType rq_type = 1;</code>
     *
     * <pre>
     *request type is required
     * </pre>
     */
    public boolean hasRqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Request.ReqType rq_type = 1;</code>
     *
     * <pre>
     *request type is required
     * </pre>
     */
    public buffers.ClientRequest.Request.ReqType getRqType() {
      return rqType_;
    }

    public static final int REG_FIELD_NUMBER = 3;
    private buffers.ClientRequest.Request.Registration reg_;
    /**
     * <code>optional .Request.Registration reg = 3;</code>
     *
     * <pre>
     *registration message will be filled in for type REG
     * </pre>
     */
    public boolean hasReg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Request.Registration reg = 3;</code>
     *
     * <pre>
     *registration message will be filled in for type REG
     * </pre>
     */
    public buffers.ClientRequest.Request.Registration getReg() {
      return reg_;
    }
    /**
     * <code>optional .Request.Registration reg = 3;</code>
     *
     * <pre>
     *registration message will be filled in for type REG
     * </pre>
     */
    public buffers.ClientRequest.Request.RegistrationOrBuilder getRegOrBuilder() {
      return reg_;
    }

    public static final int LIN_FIELD_NUMBER = 4;
    private buffers.ClientRequest.Request.LogIn lin_;
    /**
     * <code>optional .Request.LogIn lin = 4;</code>
     *
     * <pre>
     *login message will be filled in for type LIN
     * </pre>
     */
    public boolean hasLin() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Request.LogIn lin = 4;</code>
     *
     * <pre>
     *login message will be filled in for type LIN
     * </pre>
     */
    public buffers.ClientRequest.Request.LogIn getLin() {
      return lin_;
    }
    /**
     * <code>optional .Request.LogIn lin = 4;</code>
     *
     * <pre>
     *login message will be filled in for type LIN
     * </pre>
     */
    public buffers.ClientRequest.Request.LogInOrBuilder getLinOrBuilder() {
      return lin_;
    }

    public static final int USERNAME_FIELD_NUMBER = 5;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 5;</code>
     *
     * <pre>
     *username field will be filled in for types CALL, ADDF, DELF
     * </pre>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string username = 5;</code>
     *
     * <pre>
     *username field will be filled in for types CALL, ADDF, DELF
     * </pre>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 5;</code>
     *
     * <pre>
     *username field will be filled in for types CALL, ADDF, DELF
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIRMATION_FIELD_NUMBER = 6;
    private boolean confirmation_;
    /**
     * <code>optional bool confirmation = 6;</code>
     *
     * <pre>
     *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
     * </pre>
     */
    public boolean hasConfirmation() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool confirmation = 6;</code>
     *
     * <pre>
     *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
     * </pre>
     */
    public boolean getConfirmation() {
      return confirmation_;
    }

    private void initFields() {
      rqType_ = buffers.ClientRequest.Request.ReqType.REG;
      reg_ = buffers.ClientRequest.Request.Registration.getDefaultInstance();
      lin_ = buffers.ClientRequest.Request.LogIn.getDefaultInstance();
      username_ = "";
      confirmation_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasReg()) {
        if (!getReg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasLin()) {
        if (!getLin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, rqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, reg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, lin_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, confirmation_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, rqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, reg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, lin_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, confirmation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static buffers.ClientRequest.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.ClientRequest.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.ClientRequest.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.ClientRequest.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.ClientRequest.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static buffers.ClientRequest.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static buffers.ClientRequest.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static buffers.ClientRequest.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static buffers.ClientRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static buffers.ClientRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(buffers.ClientRequest.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     *
     * <pre>
     *request structure
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        buffers.ClientRequest.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffers.ClientRequest.internal_static_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffers.ClientRequest.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buffers.ClientRequest.Request.class, buffers.ClientRequest.Request.Builder.class);
      }

      // Construct using buffers.ClientRequest.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRegFieldBuilder();
          getLinFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rqType_ = buffers.ClientRequest.Request.ReqType.REG;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (regBuilder_ == null) {
          reg_ = buffers.ClientRequest.Request.Registration.getDefaultInstance();
        } else {
          regBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (linBuilder_ == null) {
          lin_ = buffers.ClientRequest.Request.LogIn.getDefaultInstance();
        } else {
          linBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        confirmation_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffers.ClientRequest.internal_static_Request_descriptor;
      }

      public buffers.ClientRequest.Request getDefaultInstanceForType() {
        return buffers.ClientRequest.Request.getDefaultInstance();
      }

      public buffers.ClientRequest.Request build() {
        buffers.ClientRequest.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public buffers.ClientRequest.Request buildPartial() {
        buffers.ClientRequest.Request result = new buffers.ClientRequest.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rqType_ = rqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (regBuilder_ == null) {
          result.reg_ = reg_;
        } else {
          result.reg_ = regBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (linBuilder_ == null) {
          result.lin_ = lin_;
        } else {
          result.lin_ = linBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.confirmation_ = confirmation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffers.ClientRequest.Request) {
          return mergeFrom((buffers.ClientRequest.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buffers.ClientRequest.Request other) {
        if (other == buffers.ClientRequest.Request.getDefaultInstance()) return this;
        if (other.hasRqType()) {
          setRqType(other.getRqType());
        }
        if (other.hasReg()) {
          mergeReg(other.getReg());
        }
        if (other.hasLin()) {
          mergeLin(other.getLin());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000008;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasConfirmation()) {
          setConfirmation(other.getConfirmation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRqType()) {
          
          return false;
        }
        if (hasReg()) {
          if (!getReg().isInitialized()) {
            
            return false;
          }
        }
        if (hasLin()) {
          if (!getLin().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buffers.ClientRequest.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buffers.ClientRequest.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private buffers.ClientRequest.Request.ReqType rqType_ = buffers.ClientRequest.Request.ReqType.REG;
      /**
       * <code>required .Request.ReqType rq_type = 1;</code>
       *
       * <pre>
       *request type is required
       * </pre>
       */
      public boolean hasRqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Request.ReqType rq_type = 1;</code>
       *
       * <pre>
       *request type is required
       * </pre>
       */
      public buffers.ClientRequest.Request.ReqType getRqType() {
        return rqType_;
      }
      /**
       * <code>required .Request.ReqType rq_type = 1;</code>
       *
       * <pre>
       *request type is required
       * </pre>
       */
      public Builder setRqType(buffers.ClientRequest.Request.ReqType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        rqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Request.ReqType rq_type = 1;</code>
       *
       * <pre>
       *request type is required
       * </pre>
       */
      public Builder clearRqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rqType_ = buffers.ClientRequest.Request.ReqType.REG;
        onChanged();
        return this;
      }

      private buffers.ClientRequest.Request.Registration reg_ = buffers.ClientRequest.Request.Registration.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          buffers.ClientRequest.Request.Registration, buffers.ClientRequest.Request.Registration.Builder, buffers.ClientRequest.Request.RegistrationOrBuilder> regBuilder_;
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public boolean hasReg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public buffers.ClientRequest.Request.Registration getReg() {
        if (regBuilder_ == null) {
          return reg_;
        } else {
          return regBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public Builder setReg(buffers.ClientRequest.Request.Registration value) {
        if (regBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reg_ = value;
          onChanged();
        } else {
          regBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public Builder setReg(
          buffers.ClientRequest.Request.Registration.Builder builderForValue) {
        if (regBuilder_ == null) {
          reg_ = builderForValue.build();
          onChanged();
        } else {
          regBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public Builder mergeReg(buffers.ClientRequest.Request.Registration value) {
        if (regBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              reg_ != buffers.ClientRequest.Request.Registration.getDefaultInstance()) {
            reg_ =
              buffers.ClientRequest.Request.Registration.newBuilder(reg_).mergeFrom(value).buildPartial();
          } else {
            reg_ = value;
          }
          onChanged();
        } else {
          regBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public Builder clearReg() {
        if (regBuilder_ == null) {
          reg_ = buffers.ClientRequest.Request.Registration.getDefaultInstance();
          onChanged();
        } else {
          regBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public buffers.ClientRequest.Request.Registration.Builder getRegBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRegFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      public buffers.ClientRequest.Request.RegistrationOrBuilder getRegOrBuilder() {
        if (regBuilder_ != null) {
          return regBuilder_.getMessageOrBuilder();
        } else {
          return reg_;
        }
      }
      /**
       * <code>optional .Request.Registration reg = 3;</code>
       *
       * <pre>
       *registration message will be filled in for type REG
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          buffers.ClientRequest.Request.Registration, buffers.ClientRequest.Request.Registration.Builder, buffers.ClientRequest.Request.RegistrationOrBuilder> 
          getRegFieldBuilder() {
        if (regBuilder_ == null) {
          regBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              buffers.ClientRequest.Request.Registration, buffers.ClientRequest.Request.Registration.Builder, buffers.ClientRequest.Request.RegistrationOrBuilder>(
                  getReg(),
                  getParentForChildren(),
                  isClean());
          reg_ = null;
        }
        return regBuilder_;
      }

      private buffers.ClientRequest.Request.LogIn lin_ = buffers.ClientRequest.Request.LogIn.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          buffers.ClientRequest.Request.LogIn, buffers.ClientRequest.Request.LogIn.Builder, buffers.ClientRequest.Request.LogInOrBuilder> linBuilder_;
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public boolean hasLin() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public buffers.ClientRequest.Request.LogIn getLin() {
        if (linBuilder_ == null) {
          return lin_;
        } else {
          return linBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public Builder setLin(buffers.ClientRequest.Request.LogIn value) {
        if (linBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lin_ = value;
          onChanged();
        } else {
          linBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public Builder setLin(
          buffers.ClientRequest.Request.LogIn.Builder builderForValue) {
        if (linBuilder_ == null) {
          lin_ = builderForValue.build();
          onChanged();
        } else {
          linBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public Builder mergeLin(buffers.ClientRequest.Request.LogIn value) {
        if (linBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              lin_ != buffers.ClientRequest.Request.LogIn.getDefaultInstance()) {
            lin_ =
              buffers.ClientRequest.Request.LogIn.newBuilder(lin_).mergeFrom(value).buildPartial();
          } else {
            lin_ = value;
          }
          onChanged();
        } else {
          linBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public Builder clearLin() {
        if (linBuilder_ == null) {
          lin_ = buffers.ClientRequest.Request.LogIn.getDefaultInstance();
          onChanged();
        } else {
          linBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public buffers.ClientRequest.Request.LogIn.Builder getLinBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLinFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      public buffers.ClientRequest.Request.LogInOrBuilder getLinOrBuilder() {
        if (linBuilder_ != null) {
          return linBuilder_.getMessageOrBuilder();
        } else {
          return lin_;
        }
      }
      /**
       * <code>optional .Request.LogIn lin = 4;</code>
       *
       * <pre>
       *login message will be filled in for type LIN
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          buffers.ClientRequest.Request.LogIn, buffers.ClientRequest.Request.LogIn.Builder, buffers.ClientRequest.Request.LogInOrBuilder> 
          getLinFieldBuilder() {
        if (linBuilder_ == null) {
          linBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              buffers.ClientRequest.Request.LogIn, buffers.ClientRequest.Request.LogIn.Builder, buffers.ClientRequest.Request.LogInOrBuilder>(
                  getLin(),
                  getParentForChildren(),
                  isClean());
          lin_ = null;
        }
        return linBuilder_;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 5;</code>
       *
       * <pre>
       *username field will be filled in for types CALL, ADDF, DELF
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string username = 5;</code>
       *
       * <pre>
       *username field will be filled in for types CALL, ADDF, DELF
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 5;</code>
       *
       * <pre>
       *username field will be filled in for types CALL, ADDF, DELF
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 5;</code>
       *
       * <pre>
       *username field will be filled in for types CALL, ADDF, DELF
       * </pre>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 5;</code>
       *
       * <pre>
       *username field will be filled in for types CALL, ADDF, DELF
       * </pre>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000008);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 5;</code>
       *
       * <pre>
       *username field will be filled in for types CALL, ADDF, DELF
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
        return this;
      }

      private boolean confirmation_ ;
      /**
       * <code>optional bool confirmation = 6;</code>
       *
       * <pre>
       *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
       * </pre>
       */
      public boolean hasConfirmation() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool confirmation = 6;</code>
       *
       * <pre>
       *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
       * </pre>
       */
      public boolean getConfirmation() {
        return confirmation_;
      }
      /**
       * <code>optional bool confirmation = 6;</code>
       *
       * <pre>
       *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
       * </pre>
       */
      public Builder setConfirmation(boolean value) {
        bitField0_ |= 0x00000010;
        confirmation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool confirmation = 6;</code>
       *
       * <pre>
       *confirmation field will be filled in for types LOUT, ECALL, FLIST, CALLRES
       * </pre>
       */
      public Builder clearConfirmation() {
        bitField0_ = (bitField0_ & ~0x00000010);
        confirmation_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Request)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_Registration_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_Registration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_LogIn_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_LogIn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024client_request.proto\"\354\002\n\007Request\022!\n\007rq" +
      "_type\030\001 \002(\0162\020.Request.ReqType\022\"\n\003reg\030\003 \001" +
      "(\0132\025.Request.Registration\022\033\n\003lin\030\004 \001(\0132\016" +
      ".Request.LogIn\022\020\n\010username\030\005 \001(\t\022\024\n\014conf" +
      "irmation\030\006 \001(\010\032@\n\014Registration\022\020\n\010userna" +
      "me\030\001 \002(\t\022\020\n\010password\030\002 \002(\t\022\014\n\004hint\030\003 \001(\t" +
      "\032+\n\005LogIn\022\020\n\010username\030\001 \002(\t\022\020\n\010password\030" +
      "\002 \002(\t\"f\n\007ReqType\022\007\n\003REG\020\001\022\007\n\003LIN\020\002\022\010\n\004LO" +
      "UT\020\003\022\010\n\004CALL\020\004\022\013\n\007CALLRES\020\005\022\t\n\005ECALL\020\006\022\t" +
      "\n\005FLIST\020\007\022\010\n\004ADDF\020\010\022\010\n\004DELF\020\tB\013\n\007buffers",
      "H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "RqType", "Reg", "Lin", "Username", "Confirmation", });
    internal_static_Request_Registration_descriptor =
      internal_static_Request_descriptor.getNestedTypes().get(0);
    internal_static_Request_Registration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Request_Registration_descriptor,
        new java.lang.String[] { "Username", "Password", "Hint", });
    internal_static_Request_LogIn_descriptor =
      internal_static_Request_descriptor.getNestedTypes().get(1);
    internal_static_Request_LogIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Request_LogIn_descriptor,
        new java.lang.String[] { "Username", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
